# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - kms-as

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # 수정내역 
      # 1. gradle buile를 위한 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        # working-directory: demo-jar # 1.프로젝트 변경시 수정사항
        working-directory: MySQL # 1.프로젝트 변경시 수정사항
      
      # 2. Gradle build 진행
      - name: Build with Gradle
        run : |
          cd MySQL
          ./gradlew build -x test # Gradle 빌드 실행
      
      # 3. path 수정
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/MySQL/build/libs/*.jar'
          # path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kms-as'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FD0A8D4D0DEE4D6099BD139D6F8B3537 }}
          package: 'SNAPSHOT.jar'
