# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - SpringBoot-MySQL-RW-as

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # 1. Build with Maven 주석처리
      # - name: Build with Maven
      #   run: mvn clean install
    
      # 2. Gradle build에 필요한 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: MySQL

      # 3. Gradle build 진행
      - name: Build with Gradle
        run : |
          cd MySQL     # 해당 디렉토리로 이동
          ./gradlew build -x test # Gradle 빌드 실행

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SpringBoot-MySQL-RW-as'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1C76F76AA1CD493CB18F9E7936677D88 }}
          package: '*SNAPSHOT.jar'
